#!/usr/bin/env python3
import sys


def solve(N: int, P: "List[int]"):
    P_sorted = sorted(P)
    result = 0
    print(P_sorted)
    for i in range(N - 1):
        # print(P_sorted[i] * (i + 1))
        result += P_sorted[i] * (i + 1)
    print(result)


# Generated by 1.1.5 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    P = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, P)

if __name__ == '__main__':
    main()
